{% set name = "xorg-util-macros" %}
{% set version = "1.20.2" %}
{% set am_version = "1.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://www.x.org/releases/individual/util/{{ name.split('-')[1] }}-{{ name.split('-')[2] }}-{{ version }}.tar.xz
  sha256: 9ac269eba24f672d7d7b3574e4be5f333d13f04a7712303b1821b2a51ac82e8e

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ stdlib('c') }}  # [linux]
    - {{ compiler('c') }}   # [linux]
    - pkg-config  # [not win]
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/share/aclocal/xorg-macros.m4  # [not win]
    - if not exist %LIBRARY_PREFIX%\share\aclocal\xorg-macros.m4 exit 1  # [win]

about:
  home: https://www.x.org
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Development utility macros for X.org software.
  description: |
    This is a set of autoconf macros used by the configure.ac scripts in
    other Xorg modular packages, and is needed to generate new versions
    of their configure scripts with autoconf.
  dev_url: https://gitlab.freedesktop.org/xorg/util/macros
  doc_url: https://gitlab.freedesktop.org/xorg/util/macros

extra:
  recipe-maintainers:
    - pkgw
    - msarahan
  skip-lints:
    - missing_tests
    - m2_must_be_updated_to_msys2
    - m2w64_must_be_updated_to_ucrt64
    - m2_must_be_updated_to_msys2
