{% set name = "xorg-util-macros" %}
{% set version = "1.20.2" %}
{% set xorg_category = "util" %}
{% set am_version = "1.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ name.split('-')[1] }}-{{ name.split('-')[2] }}-{{ version }}.tar.xz
  sha256: 9ac269eba24f672d7d7b3574e4be5f333d13f04a7712303b1821b2a51ac82e8e

build:
  number: 0
  detect_binary_files_with_prefix: true
  # skip: true  # [osx]

requirements:
  build:
    - {{ stdlib("c") }}  # [linux]
    - {{ compiler('c') }}   # [linux]
    - msys2-autoconf  # [win]
    - msys2-automake{{ am_version }}  # [win]
    - msys2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-toolchain  # [win]
    - pkg-config  # [not win]
    - msys2-posix                 # [win]
    - make  # [unix]

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Development utility macros for X.org software.
  description: |
    This is a set of autoconf macros used by the configure.ac scripts in
    other Xorg modular packages, and is needed to generate new versions
    of their configure scripts with autoconf.
  dev_url: https://gitlab.freedesktop.org/xorg/util/macros
  doc_url: https://gitlab.freedesktop.org/xorg/util/macros

extra:
  recipe-maintainers:
    - pkgw
    - msarahan
  skip-lints:
    - missing_tests
