travis:
  secure:
    BINSTAR_TOKEN: e8uepQy7AMQ0CB4qqLGcJTQp9dYz9UGVX+oKYd7CVX6JAfPNMpKq51jYsNqp4eGI12oZ56ANPN+PC1AhgLdAUFcHuYyPKLCyRaV8Kd/2YihyoAfM3QHhdwgO2pRbw10WwcouC+/Pi4MzG33/EiGbEY0uyvSPsaNW+jZoFtCO8uK2UkB3TNIFyCPlZ+g+qdHOBt1lhZc2Db7ltd5zAAUCX/sccHmda9CNNgF5WkejHOZxCCzWVV/t49Ociri6gwD7/Wu35hSHJNbzIuQ71bAA2NonA9w/kp41ecP6cuJswt+iMnl2a8uNoLCGnT0ZtF/W5bZ0MJVgwS2TA4P9wWUklvMGcoSVZmlT3ujJ7iiR8WlNR4awmZ8JI39PJtrghc802GgjkrNY8YM/JJEpZnrd1ykwvNEQ4+yxnoPeIDm4OGESd6ti2nI0OpciuULX2LV4FVIVrTNVwzUX+o+P/f/Bxg+LK7SFmWTUwm46I+bY4yE7astzEP6/bADpmFF8L9VwQq6YSt11x16meftd+zJBUZ8RtFAZJ+a+m2QBQqY0V6qfmGvg/ZjOu9lkotDO3YmVi6JwAVkIWOxREbUfzf8yjVmg7IayNdCGX6DCU/YkDTCQwyuqFQ+8ErYE7Edje9SZReVgwEjS2h5yjDlqUaFKgpvDpN5sytbE8tr614DTSyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
